### ISSUE TITLE
Gobbldygook Next (aka 3.0.0-rc1)

### ISSUE THREAD

**Issue by hawkrives** [hawkrives/gobbldygook#516]
`<description>`
## Todo – App
- [x] Finish re-enabling all of the old screens
  - [x] New Student
  - [x] Course Overlay
  - [x] Share Sheet
- [x] Merge and enable student import
## Todo – Hanson format
- [x] Fix `at most` queries
- [ ] Figure out how to properly handle dirty course tracking

**Comment by hawkrives** [comment]
Right, well, I'm going to ship a new beta for stable shortly.
